### Merging old data

In [28]:
import pandas as pd

In [29]:
dev = pd.read_json('dev.json', lines=True)
test = pd.read_json('test.json', lines=True)
train = pd.read_json('train.json', lines=True)

In [30]:
df = pd.concat([dev, test, train])

In [31]:
dev

,sentence,s_start,ner,relation,event,id
0,"[Physicians, should, be, aware, that, PLP, can...",0,[],[],"[[[7, 7, Adverse_event], [5, 5, Effect], [11, ...",109073913
1,"[Heparin, -, dependent, antibodies, and, throm...",0,[],[],"[[[9, 9, Adverse_event], [10, 10, Effect], [7,...",189570003
2,"[Treatment, of, lithium, tremor, with, metopro...",0,[],[],"[[[0, 1, Potential_therapeutic_event], [5, 5, ...",64056331
3,"[A, 54, -, year, -, old, man, ,, treated, with...",0,[],[],"[[[12, 12, Adverse_event], [0, 6, Subject], [1...",40442221
4,"[Gynaecomastia, is, a, rarely, reported, adver...",0,[],[],"[[[5, 7, Adverse_event], [0, 0, Effect], [10, ...",129624652
...,...,...,...,...,...,...
956,"[Successful, challenge, with, clozapine, in, a...",0,[],[],"[[[2, 2, Potential_therapeutic_event], [3, 3, ...",99883653
957,"[CASE, SUMMARY, :, A, 57, -, year, -, old, fem...",0,[],[],"[[[31, 32, Adverse_event], [3, 21, Subject], [...",163527771
958,"[Acute, intravascular, hemolysis, developed, w...",0,[],[],"[[[10, 10, Adverse_event], [5, 7, Subject], [0...",65102232
959,"[Intravitreal, triamcinolone, may, have, had, ...",0,[],[],"[[[6, 6, Adverse_event], [17, 18, Subject], [9...",175057391
960,"[We, evaluated, a, patient, who, developed, a,...",0,[],[],"[[[5, 5, Adverse_event], [3, 3, Subject], [7, ...",89617302

In [32]:
test

,sentence,s_start,ner,relation,event,id
0,"[After, therapy, with, parenteral, amiodarone,...",0,[],[],"[[[0, 0, Adverse_event], [27, 52, Effect], [3,...",37089491
1,"[We, report, one, case, of, non, -, Hodgkin, l...",0,[],[],"[[[23, 23, Adverse_event], [10, 21, Subject], ...",84676203
2,"[We, recommend, the, cautious, use, of, alum, ...",0,[],[],"[[[19, 19, Adverse_event], [9, 9, Subject], [2...",14224976
3,"[RESULTS, :, A, 44, -, year, -, old, man, taki...",0,[],[],"[[[29, 29, Adverse_event], [17, 23, Subject], ...",100825973
4,"[CASE, REPORT, :, We, report, a, case, of, int...",0,[],[],"[[[10, 10, Adverse_event], [13, 21, Subject], ...",160181641
...,...,...,...,...,...,...
963,"[An, 89, -, year, -, old, man, receiving, long...",0,[],[],"[[[7, 7, Potential_therapeutic_event], [0, 6, ...",215158653
964,"[Treatment, with, tifacogin, had, no, effect, ...",0,[],[],"[[[5, 5, Adverse_event], [12, 18, Subject], [1...",1285127914
965,"[Although, lung, specimens, were, lacking, fro...",0,[],[],"[[[23, 23, Adverse_event], [7, 8, Subject], [7...",65725421
966,"[Concomitant, use, of, clarithromycin, or, oth...",0,[],[],"[[[13, 13, Adverse_event], [15, 25, Effect], [...",1145224511
967,"[Drug, -, induced, fever, due, to, diltiazem, .]",0,[],[],"[[[4, 5, Adverse_event], [3, 3, Effect], [6, 6...",18882561

In [33]:
train

,sentence,s_start,ner,relation,event,id
0,"[OBJECTIVE, :, To, test, the, hypothesis, that...",0,[],[],"[[[29, 29, Adverse_event], [30, 30, Effect], [...",89083963
1,"[An, evaluation, of, ovarian, structure, and, ...",0,[],[],"[[[25, 25, Adverse_event], [11, 14, Subject], ...",108919911
2,"[Phenobarbital, hepatotoxicity, in, an, 8, -, ...",0,[],[],"[[[2, 2, Adverse_event], [3, 9, Subject], [4, ...",23325961
3,"[The, authors, report, a, case, of, Balint, sy...",0,[],[],"[[[14, 14, Adverse_event], [6, 13, Effect], [1...",125520541
4,"[According, to, the, Naranjo, probability, sca...",0,[],[],"[[[11, 11, Adverse_event], [13, 14, Subject], ...",1953169512
...,...,...,...,...,...,...
2893,"[L, -, T4, stimulated, lymphocyte, transformat...",0,[],[],"[[[3, 3, Adverse_event], [7, 8, Subject], [4, ...",29314453
2894,"[A, 53, -, year, -, old, man, developed, lower...",0,[],[],"[[[13, 13, Adverse_event], [0, 6, Subject], [1...",121262251
2895,"[A, mentally, retarded, 23, -, year, -, old, w...",0,[],[],"[[[25, 25, Adverse_event], [0, 12, Subject], [...",31435512
2896,"[After, 5, days, of, treatment, with, IL, -, 2...",0,[],[],"[[[12, 12, Adverse_event], [11, 11, Subject], ...",120865491
2897,"[Acute, pancreatitis, after, long, -, term, 5,...",0,[],[],"[[[2, 2, Adverse_event], [0, 1, Effect], [3, 1...",93997761

In [34]:
df.reset_index(inplace=True, drop=True)

In [35]:
df.to_json("merged.json", orient="records", lines=True)

### New division

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split



df = pd.read_json('merged.json', lines=True)

train_df, temp_df = train_test_split(
    df,
    test_size=0.3,
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42
)

print(len(train_df), len(val_df), len(test_df))

3378 724 725

In [3]:
train_df.reset_index(inplace=True, drop=True)
val_df.reset_index(inplace=True, drop=True)
test_df.reset_index(inplace=True, drop=True)

In [4]:
train_df.to_json("train_main.json", orient="records", lines=True)
val_df.to_json("val_main.json", orient="records", lines=True)
test_df.to_json("test_main.json", orient="records", lines=True)